### ISSUE TITLE
Bug: Client error during enrollment

### ISSUE THREAD

**Issue by JamesDodds** [garysharp/Disco#102]
When enrolling workstations with no wireless hardware, the client attempts to connect to the local wireless service. As this doesn't exist, it causes a fatal error in the client and halts the process.

> IP: XXX.YYY.ZZZ.AAA; Device ID: SNID; Version: Disco-Client/2.2.16280 Error: Unable to connect to local wireless service. WlanOpenHandle returned: 1062

**Comment by garysharp** [comment]
Thanks James. The error indicates:
`The service has not been started.`
https://msdn.microsoft.com/en-us/library/windows/desktop/ms681383(v=vs.85).aspx

Which makes sense for the scenario you mentioned. I'll have this fixed shortly.
