### ISSUE TITLE
Possible Enhancement

### ISSUE THREAD

**Issue by andymitchellau** [garysharp/Disco#105]
Hi,
Just was wondering if it was possible to have teachers being able to reset student passwords but not other staff members in Disco?

**Comment by conorvahland** [comment]
as the Password plugin honors the underlying AD policy objects (complexity, last change, etc) i would presume you could configure your AD with the appropriate Delegate Control objects allowing staff to change password rights for the students OU. In AD by default staff should not be able to change other staff passwords (im pretty sure)

**Comment by garysharp** [comment]
Spot on @conorvahland.

You'll probably want to create an Authorization Role in Disco ICT (Configuration > Authorization Roles) and link it to your Staff group. Then provide at least the following permissions:
- User > Search Users
- User > Show Users
*(hovering over any permission provides a little more information in the tooltip)*

This will allow staff to find any user, but the plugin will only provide the option to Change Password when they have the underling delegated permission in AD.
