### ISSUE TITLE
Document importer errors occasionally

### ISSUE THREAD

**Issue by mattmuschalla** [garysharp/Disco#110]
When scanning/dropping documents into a Disco DocumentDropBox share, files at random will upload to student profile and not set any flags, sometimes files will be attached to student profile multiple times upon disco's automatic retry, sometimes no files are attached at all. 
Disco logging gives errors (shown below)

**Comment by mattmuschalla** [comment]
08/02/2018 02:35:35 PM	Import Finished	Import of document complete (SessionId: c7dcabe5-41be-4244-8166-87cb205bf8a6)
08/02/2018 02:35:35 PM	Exception with Inner Exception	Document Importer - OnImportAttachmentExpression; InvalidOperationException: Expression evaluation resulted in an error; at Disco.Services.Expressions.Expression.EvaluateFirst[T](Object ExpressionContext, IDictionary Variables)
 at Disco.Services.DocumentTemplateExpressionExtensions.EvaluateOnAttachmentImportExpression(DocumentTemplate dt, IAttachment Data, DiscoDataContext Database, User User, DateTime TimeStamp, List`1 PageIdentifiers)
 at Disco.Services.Documents.AttachmentImport.Importer.ImportPdfAttachment(DocumentUniqueIdentifier Identifier, DiscoDataContext Database, Stream PdfContent, Image Thumbnail, List`1 PageIdentifiers); DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.; at System.Data.Entity.Internal.InternalContext.SaveChanges()
 at Disco.Data.Repository.DiscoDataContext.SaveChanges()
 at _dynamic_Disco.Data.Repository.DiscoDataContext.SaveChanges(Object , Object[] )
 at Spring.Expressions.MethodNode.Get(Object context, EvaluationContext evalContext)
 at Spring.Expressions.Expression.Get(Object context, EvaluationContext evalContext)
 at Spring.Expressions.ExpressionListNode.Get(Object context, EvaluationContext evalContext)
 at Spring.Expressions.Expression.Get(Object context, EvaluationContext evalContext)
 at Spring.Expressions.TernaryNode.Get(Object context, EvaluationContext evalContext)
 at Spring.Expressions.ExpressionListNode.Get(Object context, EvaluationContext evalContext)
 at Spring.Expressions.Expression.Get(Object context, EvaluationContext evalContext)
 at Disco.Services.Expressions.Expression.EvaluateFirst[T](Object ExpressionContext, IDictionary Variables)
08/02/2018 02:35:35 PM	Exception	User Flag Expression - OnAssignmentExpression; DbEntityValidationException: Validation failed for one or more entities:
 'UserFlagAssignment' Object
 AddedUserId: The AddedUserId field is required.
 ; at System.Data.Entity.Internal.InternalContext.SaveChanges()
 at Disco.Data.Repository.DiscoDataContext.SaveChanges()
 at Disco.Services.UserFlagExtensions.OnAddUserFlagUnsafe(User u, DiscoDataContext Database, UserFlag flag, User AddingUser, String Comments)
08/02/2018 02:35:35 PM	Import Page Assigned	Page 1 of type 'Acceptable Usage Agreement' assigned to User: 'Riely Nelson (BHS1\NEL0015)'
08/02/2018 02:35:35 PM	Import Page Starting	Starting import of page: 1 (SessionId: c7dcabe5-41be-4244-8166-87cb205bf8a6)
08/02/2018 02:35:35 PM	Import Starting	Starting import of document: S22C-118020813342.pdf (SessionId: c7dcabe5-41be-4244-8166-87cb205bf8a6)

**Comment by garysharp** [comment]
From the stack trace you provided (thank you) it would seem that the problem lies in the custom 'On Import Expression' associated with the Document Template. Can you please share this expression?

**Comment by mattmuschalla** [comment]
(
User.UserFlagAssignments.?{
    UserFlagId==15 and RemovedDate==null
  }.count() > 0
  ? #message = 'User Flag Already Present'
  : (
    #flag = #DataContext.UserFlags.Find(15);
    #comment = 'Automatically added by ' + DocumentTemplate.Description + ' document';

    T(Disco.Services.UserFlagExtensions).OnAddUserFlag(User, #DataContext, #flag, #User, #comment);
    #DataContext.SaveChanges();
    #message = 'User Flag Added'
    );


#adInterop = T(Disco.Services.Interop.ActiveDirectory.ActiveDirectory);
#adAccount = #adInterop.RetrieveADUserAccount(User.UserId, 'userAccountControl');
#adCurrentUAC = #adAccount.LoadedProperties['userAccountControl'][0];
(#adCurrentUAC and 2) == 0
  ? #message = #message + ', AD Account Already Enabled'
  : (
    #adEntry = #adInterop.Context.GetDomainFromId(User.UserId)
        .GetAvailableDomainController(true)
        .RetrieveDirectoryEntry(#adAccount.DistinguishedName, new string[] {'userAccountControl'});
    #adEntry.Entry.Properties['userAccountControl'][0] = (#adCurrentUAC xor 2);
    #adEntry.Entry.CommitChanges();
    #message = #message + ', AD Account Enabled'
    );

#message
)

**Comment by mattmuschalla** [comment]
Hi Gary, Here's our other 'On Import Expression' that seems to be having the same issue as the previously mentioned one. A duplicate other then the UserFlagId from what I can see  -

(
User.UserFlagAssignments.?{
    UserFlagId==13 and RemovedDate==null
  }.count() > 0
  ? #message = 'User Flag Already Present'
  : (
    #flag = #DataContext.UserFlags.Find(13);
    #comment = 'Automatically added by ' + DocumentTemplate.Description + ' document';

    T(Disco.Services.UserFlagExtensions).OnAddUserFlag(User, #DataContext, #flag, #User, #comment);
    #DataContext.SaveChanges();
    #message = 'User Flag Added'
    );


#adInterop = T(Disco.Services.Interop.ActiveDirectory.ActiveDirectory);
#adAccount = #adInterop.RetrieveADUserAccount(User.UserId, 'userAccountControl');
#adCurrentUAC = #adAccount.LoadedProperties['userAccountControl'][0];
(#adCurrentUAC and 2) == 0
  ? #message = #message + ', AD Account Already Enabled'
  : (
    #adEntry = #adInterop.Context.GetDomainFromId(User.UserId)
        .GetAvailableDomainController(true)
        .RetrieveDirectoryEntry(#adAccount.DistinguishedName, new string[] {'userAccountControl'});
    #adEntry.Entry.Properties['userAccountControl'][0] = (#adCurrentUAC xor 2);
    #adEntry.Entry.CommitChanges();
    #message = #message + ', AD Account Enabled'
    );

#message
)


Cheers,
Matt

**Comment by garysharp** [comment]
Hi @mattmuschalla, thanks for providing that information. On a more closer inspection of the stack trace the problem appears to actually be in a User Flag On Assignment Expression:

> at Disco.Services.Expressions.Expression.EvaluateFirst[T](Object ExpressionContext, IDictionary Variables)
> 08/02/2018 02:35:35 PM **Exception User Flag Expression - OnAssignmentExpression**; DbEntityValidationException: Validation failed for one or more entities:
> 'UserFlagAssignment' Object
> **AddedUserId: The AddedUserId field is required.**

This is difficult to immediately see as it is a **Document Template On Import Expression** which is **creating a User Flag assignment**; which in turn is causing the **User Flag On Assignment Expression** to be evaluated.

Has this behavior been considered? Perhaps you only need one or the other. Are they doing the same thing?

Can you please share the User Flag On Assignment Expression (for both flags 13 and 15). If both document template and user flag expressions are needed I have a suspicion about what the cause might be and how it can easily be fixed.

**Comment by mattmuschalla** [comment]
Our 2018 New Users User Flag On Assignment Expression:

#adInterop = T(Disco.Services.Interop.ActiveDirectory.ActiveDirectory);
#adAccount = #adInterop.RetrieveADUserAccount(User.UserId, 'userAccountControl');
#adCurrentUAC = #adAccount.LoadedProperties['userAccountControl'][0];
(#adCurrentUAC and 2) == 0
  ? #message = #message + ', AD Account Already Enabled'
  : (
    #adEntry = #adInterop.Context.GetDomainFromId(User.UserId)
        .GetAvailableDomainController(true)
        .RetrieveDirectoryEntry(#adAccount.DistinguishedName, new string[] {'userAccountControl'});
    #adEntry.Entry.Properties['userAccountControl'][0] = (#adCurrentUAC xor 2);
    #adEntry.Entry.CommitChanges();
    #message = #message + ', AD Account Enabled'
    );

#message
)


And our BYOD Student Users User Flag does not have an On Assignment Expression, it just has "Linked Groups: Assigned Users Linked Group"

**Comment by garysharp** [comment]
Hi @mattmuschalla,
I think I found the problem. There was an edge-case not accounted for if the UserCache contained the technician's user entity (the one who originally generated the document). A single line of code was changed. I've published this to your deployment (as I have been previously given RDP access to your Disco ICT server and your organisation is part of the alpha-testing team).
Please let me know if this fixes the problem.
Gary

**Comment by mattmuschalla** [comment]
Hi Gary,
It would seem that we're still having the same issues - I've just noticed that documents generated by certain technicians are not adding flags on import as expected whereas some are. I'm amusing this due to the Technician name shown under the attached documents name in Disco being recurrent for the documents without flags.
Cheers,
Matt

**Comment by mattmuschalla** [comment]
All sorted! Thanks for your help Gary
