### ISSUE TITLE
Email Account Activation

### ISSUE THREAD

**Issue by Rubber-Ducky91** [garysharp/Disco#112]
Hi there,

I am a ST apart of the TSSP program. I tried to register my education account on your website however I never got the email address confirmation email so my account hasn't been activated. I cannot log in nor recreate a new account. If you could please have a look into this that would be great. Thanks 

Tim Silvey

**Comment by garysharp** [comment]
Hi Tim,
Sorry I missed this. Can you confirm whether this is still the case? If so, I'll investigate further.

**Comment by Rubber-Ducky91** [comment]
Hey mate,

Yes this is still the case

**Comment by garysharp** [comment]
I do see your account present in the database - I've sent a new temporary password - please change it after logging in. Let me know if you have any trouble getting in.
