### ISSUE TITLE
Amount of Devices Assigned

### ISSUE THREAD

**Issue by Patrick7812** [garysharp/Disco#122]
I was curious if there was a way i could search by the amount of devices assigned to a single user. Our system has become quite cluttered with people having devices assigned to them that shouldn't be, and there being a way to search for instances where a single user has multiple devices assigned to them would be greatly helpful.

**Comment by garysharp** [comment]
You can export all devices (Devices > Export Devices) and use Excel to filter Assigned Users that have multiple entries ([plenty of online guides](https://www.bing.com/search?q=excel+filter+duplicates+in+column)).

Alternatively, the following SQL will show users with multiple devices assigned:
```SQL
SELECT
	d.AssignedUserId
	,STRING_AGG(d.SerialNumber, '; ') [SerialNumbers]
FROM dbo.Devices d
WHERE d.AssignedUserId IS NOT NULL
GROUP BY d.AssignedUserId
HAVING COUNT(1) > 1
```

**Comment by Patrick7812** [comment]
Thank you so much for your help Gary that worked beautifully
