### ISSUE TITLE
Feature Request: Add Email Address Field to Each Organisation

### ISSUE THREAD

**Issue by lcoulthard7891** [garysharp/Disco#156]
Feature Request: Add a field for your Organisation that you can add an email address into (Configuration -> Organisation Details). Just gives you the option to use this field for Document and Email Templates.
![screenshot](https://github.com/user-attachments/assets/0e090340-9b53-456d-8110-ea11b7274163)

**Comment by garysharp** [comment]
This has been added and will appear in future builds
