### ISSUE TITLE
Email Lodgement - option to have images attached to job ticked by default

### ISSUE THREAD

**Issue by rbeckett75** [garysharp/Disco#158]
I personally only ever attach photos directly related to the job issue

I would prefer if, when using the new Email Warranty Lodgement, that they are ticked automatically, underneath the email template.

I would always want all these photos to go to the warranty supplier, and I'm worried I'll forget to tick them one day, and have to follow up.
attaching photos always gives a faster turnaround from the supplier :)

**Comment by garysharp** [comment]
Delivered via a configurable option:
![image](https://github.com/user-attachments/assets/711231d7-828b-41c2-97a4-6bb2caf3ed8c)

Turned off by default to maintain existing behavior. The feature will be included in future builds.
