### ISSUE TITLE
Live Update Error

### ISSUE THREAD

**Issue by mickyvx** [garysharp/Disco#74]
Randomly getting a popup error in browser with the following message. Have tried different browsers and computers.

```
Live Update Error: Long Polling Failed
```

**Comment by garysharp** [comment]
Michael,

As mentioned above, unless resources were greatly constrained (“*very limited resources*”), adding more CPU/RAM/Network capacity will have no effect.

The [errors captured by your colleague](https://cloud.githubusercontent.com/assets/6406449/4297015/9db495ce-3e02-11e4-9dfb-b87c40165c2b.png) indicate the server (potentially a **proxy** if present) is denying the requests as `401 Unauthorized`. This could indicate a compatibility issue with Firefox although our test environments (which include the latest version of Firefox) work as expected.

You mention that this also occurs on the Noticeboards and displays “*refresh errors*.” The noticeboards operate differently that other pages; when they lose connection they wait for 10 seconds then try and refresh the whole page ([see code](https://github.com/garysharp/Disco/blob/7eb17a91c9978117c3de4b83c554af928838abbd/Disco.Web/Areas/Public/Views/HeldDevices/Noticeboard.cshtml#L345)). If you are getting errors when simply refreshing the page then this is an entirely different issue. If you are getting errors when the page refreshes, diagnose these errors first.

Previously, the following recommendations were made:

> [on Sep 15 2014](https://github.com/garysharp/Disco/issues/74#issuecomment-55551166)
> To diagnose why you are "constantly" receiving these messages:
> 
> * On the server: you can review relevant error messages in the logging (http://disco:9292/Config/Logging).
> * On the client: enable browser debugging (F12 shortcut key opens the debugger in most browsers) and monitor the JavaScript console and network traffic.
> 
> Most common causes:
> 
> * You leave the browser window open on a laptop/desktop which goes to sleep, and takes a period of time to reconnect to the server after waking up.
> * The Disco ICT application has very limited resources and is not able to respond to clients in a timely fashion.

-------

> [on Oct 2 2014](https://github.com/garysharp/Disco/issues/74#issuecomment-57570973)
> * Running multiple tabs could be the cause, see this post for the browser concurrent-connection/per-server limits.

Here are some additional things to try:
* Try using Internet Explorer 11. This is not an instruction to change your favourite browser, just to try and narrow down the cause/incompatibility. As mentioned above, there are valid reasons for these messages to appear, but not at the consistency you’ve described - see if IE11 reduces the number of instances.
* Remove any proxy settings from your browser. Disco (as a local service) should have a proxy exception, and if not – some proxy servers don’t like keeping long-running HTTP requests open.
* Update the `network.negotiate-auth.trusted-uris` Firefox setting (in `about:config`) to include `disco`.
* Use Fiddler to capture the traffic; if you can’t diagnose them yourself send them to us.

Please make sure you’ve considered ALL (9) of these diagnostic suggestions. If you are still experiencing issues after providing results from the each of the above suggestions we might be able to organise a TeamViewer session and do some remote diagnostics.

**Comment by mickyvx** [comment]
Gary,

Sorry for the delay. I have gone through all trouble shooting steps now and can give you the following results.

1. On the server there is no error messages showing within the Live Logging relating to any disconnects happening.
2. I have enabled debugging in both IE and Firefox and noticed the same as I captured for you in the posts above. 401 errors when trying to refresh/reconnect the pages.
3. Browser has not been opened with any other tabs but disco, even closed and reopened browser/restarted computer multiple times.
4. Disco server itself is not short on resources, probably over resourced if anything.
5. I added disco into the Firefox setting as suggested but this did not make any difference at all.
6. I have run Fiddler and captured the results for you in an archive to look at which I have just emailed you.

**Comment by garysharp** [comment]
This issue is stale.
One final recommendation would be to ensure [WebSockets is installed in IIS](https://learn.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-websocket-protocol-support#step-by-step-instructions), this would be the most reliable transport for SignalR to run over.
