### ISSUE TITLE
bootstrapper enrolling device with serial "N/A" causes the process to bug due to / character

### ISSUE THREAD

**Issue by conorvahland** [garysharp/Disco#79]
see below forum post by Mitchell
https://discoict.com.au/forum/support/configuration/2014/10/mac-address-for-serial-number.aspx

if a devices serial number incorrectly contains a "/" then this causes the show device page (and possibly the enrolment itself) to fail and try to show as a directory
may need to sanitise serial number to remove or escape the slash (unsure of other characters)
EG if a device has a serial number of "N/A" then the generated url to view the device is "http://disco:9292/Device/Show/N/A" which causes a 404 File or Directory Not Found error

corrective action is to fix serial number entered in bios but invalid characters may also lead to corruption in disco down the track

**Comment by garysharp** [comment]
Fixed by banning the '/' and '\' characters from being added.

If anyone already has these entities in their Disco ICT database let me know and we'll fix it up.
