### ISSUE TITLE
Live update errors

### ISSUE THREAD

**Issue by mickyvx** [garysharp/Disco#84]
When viewing a job or the noticeboard, there is continuous errors popping up saying that the page can't receive live updates and to ensure that you are connected to the server (see below).

![live update error](https://cloud.githubusercontent.com/assets/6406449/6384159/a27801e2-bda8-11e4-8ea8-ec54fab46df4.png)

The server is a VMware Virtual Machine, running Windows Server 2K8R2, 6GB RAM, 4 CPU cores. I have upgraded the resources from 2 CPU cores to 4, increased RAM, also just upgraded network adapter the the latest from 1GbE to 10GbE and still receiving this error.

On the localhost it appears to be fine, but from other machines ever 10 - 40 seconds this error is appearing, it is much more noticeable on the Noticeboard and keeps starting again due to the refresh errors.

We have tried from multiple computers and this error will not go away and we cannot figure out why. Recently we have migrated our virtual infrastructure and we hoped this error would go away with brand new servers + networking equipment but it still persists.

**Comment by garysharp** [comment]
Duplication of #74
