### ISSUE TITLE
Loan device

### ISSUE THREAD

**Issue by elijahsolly** [garysharp/Disco#91]
In many schools, when a device is in for warranty repair, the student can use a loan device. Tracking a loan device is sometimes a fairly manual process, especially when not recorded on paper.
I thought that we may be able to add a button above device held that says "Loan device issued" or something similar. When you click on this button you could search for a device or be presented with a list of devices that match a 'loan profile' potentially. 
If a user tries to return the original device without first clicking 'loan device returned' the user would get a message saying "There is a loan device associated with this job. Are you sure you wish to return the device" options could be "Yes", "No" and "Yes and Loan Device Returned" 
Just a thought!

**Comment by st01191** [comment]
This is a fantastic idea!

+1

**Comment by mattkrins** [comment]
You can achieve a result similar to this by simply assigning the user to multiple devices, then when you do a search for the user you can see they have multiple devices assigned and this should be a pretty good indication that something is a miss.

**Comment by st01191** [comment]
We currently do exactly that, but we also have some students with multiple devices so it can cause confusion at times. We should create a seperate device profile for loan units with a different image to stop this. I'm not sure why I have not done this yet... I may just do it today!

**Comment by conorvahland** [comment]
you could also create a User Flag to make the loan device more noticeable

**Comment by garysharp** [comment]
Issue has lost traction with viable alternatives suggested. Happy to re-open if theres interest.
