### ISSUE TITLE
SSH Connections fail in OSX 10.11 Clients. 

### ISSUE THREAD

**Issue by doojfa** [garysharp/Disco#92]
OSX 10.11 updated it's openssh server version to 6.9. As such it disabled default support for several key exchange methods and ciphers used in the SharpSSH Library. Including the Diffe-hellman-group1-sha1. 

Problem present itself as an exception thrown in the Device Enrolment Process: 
An Error Occurred: [JSchException] Algorithm negotiation fail. 
This then causes the device to fail enrolment. 

Suggested fix is to update the SSH library used in the MacSecureEnrol Method to one that supports stronger key exchange and ciphers that are supported by default in 10.11 and openssh 6.9. 

A Sample Packet Capture from a 10.11 client running openssh-server 6.9 on default settings. This shows the default standards. At least one common Cipher and one key exchange method is required to support a successful ssh connection. 

Server: Key Exchange Init
ssh.kex_algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1

ssh.encryption_algorithms_server_to_client: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com

**Comment by garysharp** [comment]
Fixed in 44f6d32
