### ISSUE TITLE
Device import validation

### ISSUE THREAD

**Issue by mattkrins** [garysharp/Disco#93]
Unable to import devices with just serial,user - needs to an an extra column such as profile or the import will fail with "successfully imported 0 devices".

![image](https://cloud.githubusercontent.com/assets/2367602/11356515/940d3b24-92b2-11e5-9579-761dcb6fb2f6.png)

**Comment by garysharp** [comment]
Hey Matt,

This was corrected in 669de7e. See #76 for more information. Thanks for reporting.
