### ISSUE TITLE
Decommission details

### ISSUE THREAD

**Issue by JamesDodds** [garysharp/Disco#96]
If Disco could update AD with the decommission date and/or reason, that'd be really handy.
It looks like the device gets disabled in AD around [line 123](https://github.com/garysharp/Disco/blob/master/Disco.BI/BI/Extensions/DeviceActionExtensions.cs#L123). Could the description be updated at that time as well?

**Comment by garysharp** [comment]
Requested functionality included in 0f20b16

This will also trigger an update of all AD device descriptions upon upgrade. This full update can be manually triggered via:
{Disco Server}/API/System/UpdateADDeviceDescriptions
